//SCRIPTER

//DECLARATIVE
pipeline {
    agent any
    // agent { docker { image 'maven:3.9.4' } }
    environment {
        dockerHome = tool 'myDocker'
        mavenHome = tool 'myMaven'
        PATH = "$dockerHome/bin:$mavenHome/bin:$PATH"
    }
    stages {
        stage('Checkout') {
            steps {
                echo 'Build'
                sh 'mvn --version'
                sh 'docker --version'
                echo "Path: $PATH"
                echo "Build number: $env.BUILD_NUMBER"
            }
        }
        stage('Compile') {
            steps {
                sh "mvn -f /currency-exchange-microservice/pom.xml clean compile"
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
    }
    post {
        always {
            echo 'I am awesome'
        }
        success {
            echo 'I got success'
        }
        failure {
            echo 'failed'
        }
    }
}
