//SCRIPTER

//DECLARATIVE
pipeline {
    agent any
    // agent { docker { image 'maven:3.9.4' } }
    environment {
        dockerHome = tool 'myDocker'
        mavenHome = tool 'myMaven'
        PATH = "$dockerHome/bin:$mavenHome/bin:$PATH"
    }
    stages {
        stage('Checkout') {
            steps {
                echo 'Build'
                sh 'mvn --version'
                sh 'docker --version'
                echo "Path: $PATH"
                echo "Build number: $env.BUILD_NUMBER"
            }
        }
        stage('Compile') {
            steps {
                sh 'mvn -f /var/jenkins_home/workspace/pipeline-jenkins/currency-exchange-microservice/pom.xml clean compile'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -f /var/jenkins_home/workspace/pipeline-jenkins/currency-exchange-microservice/pom.xml test'
            }
        }
        stage('Package') {
            steps {
                sh 'mvn -f /var/jenkins_home/workspace/pipeline-jenkins/currency-exchange-microservice/pom.xml package -DskipTests'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("sgaur30ash/curr-exchange:${env.BUILD_TAG}")
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('', 'dockerID') {
                        dockerImage.push()
                        dockerImage.pus('latest')
                    }
                }
            }
        }
    }
    post {
        always {
            echo 'I am awesome'
        }
        success {
            echo 'I got success'
        }
        failure {
            echo 'failed'
        }
    }
}
